name: Auto-Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
    - name: 'Auto-assign issue'
      uses: actions/github-script@v5
      with:
        script: |
          const { owner, repo, issue_number } = context.issue;
          const response = await github.issues.listComments({
            owner: owner,
            repo: repo,
            issue_number: issue_number,
          });

          const comments = response.data;
          if (comments.length === 0) {
            core.setFailed("No comments found on the issue.");
            return;
          }

          const lastComment = comments[comments.length - 1];
          const nextAssignee = lastComment.user.login;
          core.setOutput("next_assignee", nextAssignee);

    - name: Assign issue to next commenter
      if: steps.auto-assign.outputs.next_assignee
      run: |
        echo "Assigning issue to ${{ steps.auto-assign.outputs.next_assignee }}"
        gh issue assign ${{ steps.auto-assign.outputs.next_assignee }} --issue ${{ github.event.issue.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
